export const reducerCase = {
  SET_USER: "SET_USER",
  SHOW_SLIDE: "SHOW_SLIDE",
  SHOW_MESSAGE_CURRENT_USER: "SHOW_MESSAGE_CURRENT_USER",
  ALL_USERS_FROM_DB: "ALL_USERS_FROM_DB",
  CURRENT_MESSAGE_USER: "CURRENT_MESSAGE_USER",
  ALL_MESSAGES: "ALL_MESSAGES",
  ADD_MESSAGE: "ADD_MESSAGE",
  SET_SOCKET: "SET_SOCKET",
  LOADING: "LOADING",
};
